runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: "0d"

libraries:
- name: webapp2
  version: latest

- name: MySQLdb
  version: latest

- name: django
  version: latest

- name: pycrypto
  version: latest

- name: lxml
  version: latest

- name: endpoints
  version: 1.0

- name: jinja2
  version: latest

- name: ssl
  version: latest

- name: numpy
  version: latest

builtins:
- remote_api: on
- appstats: on

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : ''

handlers:
- url: /data_collector/.*|^/data_collector$
  script: DataCollector.app

- url: /_ah/admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: main.app
